### ISSUE TITLE
Error in build.panel() - - you need to download data first?

### ISSUE THREAD

**Issue by JeanCoburn** [floswald/psidR#39]
Hello, 

I'm having some trouble running something that ran about two weeks ago. Everything works fine until I run the build panel command and then I get the following error:

Error in build.panel(datadir = NULL, fam.vars = f1) : 
  No .rda or .RData files found in directory
 you need to download data first.

Any guidance you can offer would be very much appreciated. 

Kind regards, 
Allegra

**Comment by floswald** [comment]
Hard to say away from computer . I would supply a valid directory instead
of NULL?

**Comment by JeanCoburn** [comment]
Thank you for responding so quickly. I did try that, but it didn't seem to work. I also tried to run some of your example code (which works), and the only difference is that you example has no NA slots, so I thought it might have something to do with that? My famvars data looks like this:

  year head_cond_limit_am head_cond_lim_ki health_lim ill_month 
1 1968               <NA>             <NA>       <NA>       V215
2 1969               V744             V743       V745       <NA>
3 1970              V1410            V1409      V1411       <NA>
4 1971              V2122            V2121      V2123       <NA>
5 1972               <NA>             <NA>       <NA>       <NA>
6 1973               <NA>             <NA>       <NA>       <NA>
  ill_month_cost  length_limit  head_health_di  fam_health_work 
1            <NA>          <NA>            <NA>             <NA>
2            <NA>          V746            V747             V748
3            <NA>         V1412           V1413            V1414
4            <NA>         V2124           V2125            V2126
5            <NA>         V2720           V2721            V2722
6            <NA>         V3246           V3247             <NA>
  cond_lim_am  cond_lim_ki  care_req  care_re_oth 
1         <NA>         <NA>      <NA>         <NA>
2         <NA>         <NA>      <NA>         V752
3         <NA>         <NA>      <NA>        V1418
4         <NA>         <NA>      <NA>        V2130
5        V2718         <NA>      <NA>        V2726
6        V3244         <NA>      <NA>         <NA>

Thanks again.

**Comment by JeanCoburn** [comment]
Hello again, 

I'm running the same command and again getting a different error, which is strange. I'm wondering if it might have anything to do with the NA's? The example of yours that I ran had no NA's. I mentioned that everything ran fine two weeks ago, so I'm not really sure what could have changed. 

The new error I get is

Error in load(file = ind.file, envir = tmp.env) : 
  bad restore file magic number (file may be corrupted) -- no data loaded
In addition: Warning message:
file ‘IND2017ER.txt’ has magic number '4   1'
  Use of save versions prior to 2 is deprecated

**Comment by JeanCoburn** [comment]
Ok, the new error above stopped happening when I restarted R. I think I'll just post the code here in case anything stands out as incorrect. Thanks again. 

```
library(psidR)
library(openxlsx)
library(plyr)

cwf <- read.xlsx("http://psidonline.isr.umich.edu/help/xyr/psid.xlsx") 

head_cond_limit_am <- getNamesPSID("V744", cwf, years = NULL)
head_cond_limit_am <- rename(head_cond_limit_am,c('variable'='head_cond_limit_am'))

head_cond_lim_ki <- getNamesPSID("V743", cwf, years = NULL)
head_cond_lim_ki <- rename(head_cond_lim_ki, c('variable' = 'head_cond_lim_ki'))

health_lim <- getNamesPSID("V745", cwf, years = NULL)
health_lim <- rename(health_lim, c('variable' = 'health_lim'))

#sart of excel generated commands
ill_month <- getNamesPSID("V215", cwf, years = NULL)
ill_month_cost <- getNamesPSID("V6107", cwf, years = NULL)
length_limit <- getNamesPSID("V746", cwf, years = NULL)
head_health_di <- getNamesPSID("V747", cwf, years = NULL)
fam_health_work <- getNamesPSID("V748", cwf, years = NULL)
cond_lim_am <- getNamesPSID("V2718", cwf, years = NULL)
cond_lim_ki <- getNamesPSID("V4766", cwf, years = NULL)
care_req <- getNamesPSID("V6106", cwf, years = NULL)
care_re_oth <- getNamesPSID("V752", cwf, years = NULL)

ill_month <- rename(ill_month, c('variable' = 'ill_month ' ))
ill_month_cost <- rename(ill_month_cost, c('variable' = 'ill_month_cost ' ))
length_limit <- rename(length_limit, c('variable' = 'length_limit ' ))
head_health_di <- rename(head_health_di, c('variable' = 'head_health_di ' ))
fam_health_work <- rename(fam_health_work, c('variable' = 'fam_health_work ' ))
cond_lim_am <- rename(cond_lim_am, c('variable' = 'cond_lim_am ' ))
cond_lim_ki <- rename(cond_lim_ki, c('variable' = 'cond_lim_ki ' ))
care_req <- rename(care_req, c('variable' = 'care_req ' ))
care_re_oth <- rename(care_re_oth, c('variable' = 'care_re_oth ' ))

#Merging multiple data frames
f1 <- Reduce(merge, list(head_cond_limit_am, head_cond_lim_ki, health_lim, ill_month, ill_month_cost, length_limit, head_health_di, fam_health_work, cond_lim_am, cond_lim_ki, care_req, care_re_oth))

# We need to get rid of the Y preceeding the years and then destring the year variable
f1$year <- sub("Y", "", f1$year)

f1$year <- as.numeric(f1$year)

d <- build.panel(datadir=NULL,fam.vars=f1)
# must enter PSID username and password

```

**Comment by floswald** [comment]
So the issue is resolved?

**Comment by JeanCoburn** [comment]
Sorry, I'm being unclear. The original issue isn't resolved and I can't figure out why. I tried converting the psid names in the famvars file to strings, but still got the same error. 

```
 Error in build.panel(datadir = NULL, fam.vars = f1) :
No .rda or .RData files found in directory
you need to download data first.
```

I ran some of your example code and that worked, but the example had no NA values in the famvars file. I also tried to collapse my famvars file to test whether it worked when there are no NA variables - it also does, but doesn't allow me to pull all the data I need at once. So I thought that the NA variables might be at the root of the issue, but I'm not really sure. 

Sorry again for the confusion. Any advice you have would be very much appreciated.

**Comment by floswald** [comment]
Can you please post the entire code that leads to this error in a fresh R
session here?

Also please show me the content of your datadir.

**Comment by JeanCoburn** [comment]
Hello again, 

That is the entire code that leads to the error. It did work before. And there is nothing in my datadir - I was using the tmpdir while figuring things out. The reason I reran the code above (which gives me the posted error) is that I tried to run the code (for more variables) below which gave me the same error. So I went back to this code to see what the difference was and for some reason it stopped working and gave me the same error. Am I doing something wrong?

Thank you, 
Allegra

```

library(psidR)
library(openxlsx)
library(plyr)

cwf <- read.xlsx("http://psidonline.isr.umich.edu/help/xyr/psid.xlsx") 

ER33837 <- getNamesPSID("ER33837", cwf, years = NULL)
ER33535 <- getNamesPSID("ER33535", cwf, years = NULL)
V1164 <- getNamesPSID("V1164", cwf, years = NULL)
V732 <- getNamesPSID("V732", cwf, years = NULL)
V733 <- getNamesPSID("V733", cwf, years = NULL)
V82 <- getNamesPSID("V82", cwf, years = NULL)
V11905 <- getNamesPSID("V11905", cwf, years = NULL)
V734 <- getNamesPSID("V734", cwf, years = NULL)
V278 <- getNamesPSID("V278", cwf, years = NULL)
V11898 <- getNamesPSID("V11898", cwf, years = NULL)
V11899 <- getNamesPSID("V11899", cwf, years = NULL)
V11900 <- getNamesPSID("V11900", cwf, years = NULL)
ER3711 <- getNamesPSID("ER3711", cwf, years = NULL)
ER3712 <- getNamesPSID("ER3712", cwf, years = NULL)
ER23735 <- getNamesPSID("ER23735", cwf, years = NULL)
ER48944 <- getNamesPSID("ER48944", cwf, years = NULL)
ER16404 <- getNamesPSID("ER16404", cwf, years = NULL)
ER27694 <- getNamesPSID("ER27694", cwf, years = NULL)
ER16408 <- getNamesPSID("ER16408", cwf, years = NULL)
ER27698 <- getNamesPSID("ER27698", cwf, years = NULL)
V7297 <- getNamesPSID("V7297", cwf, years = NULL)
V7310 <- getNamesPSID("V7310", cwf, years = NULL)
ER16407 <- getNamesPSID("ER16407", cwf, years = NULL)
ER27697 <- getNamesPSID("ER27697", cwf, years = NULL)
ER16405 <- getNamesPSID("ER16405", cwf, years = NULL)
ER27695 <- getNamesPSID("ER27695", cwf, years = NULL)
ER16403 <- getNamesPSID("ER16403", cwf, years = NULL)
ER27693 <- getNamesPSID("ER27693", cwf, years = NULL)
ER16406 <- getNamesPSID("ER16406", cwf, years = NULL)
ER27696 <- getNamesPSID("ER27696", cwf, years = NULL)
ER16412   <- getNamesPSID("ER16412  ", cwf, years = NULL)
ER16402    <- getNamesPSID("ER16402   ", cwf, years = NULL)
ER27692 <- getNamesPSID("ER27692", cwf, years = NULL)
ER37734 <- getNamesPSID("ER37734", cwf, years = NULL)
ER37735 <- getNamesPSID("ER37735", cwf, years = NULL)
ER37732 <- getNamesPSID("ER37732", cwf, years = NULL)
ER37733 <- getNamesPSID("ER37733", cwf, years = NULL)

ER33837 <- rename(ER33837, c('variable' = 'ER33837'))
ER33535 <- rename(ER33535, c('variable' = 'ER33535'))
V1164 <- rename(V1164, c('variable' = 'V116 4'))
V732 <- rename(V732, c('variable' = 'V732'))
V733 <- rename(V733, c('variable' = 'V733'))
V82 <- rename(V82, c('variable' = 'V82'))
V11905 <- rename(V11905, c('variable' = 'V11905'))
V734  <- rename(V734, c('variable' = 'V734'))
V278 <- rename(V278, c('variable' = 'V278'))
V11898 <- rename(V11898, c('variable' = 'V11898'))
V11899 <- rename(V11899, c('variable' = 'V11899'))
V11900 <- rename(V11900, c('variable' = 'V11900'))
ER3711 <- rename(ER3711, c('variable' = 'ER3711'))
ER3712 <- rename(ER3712, c('variable' = 'ER3712'))
ER23735 <- rename(ER23735, c('variable' = 'ER23735'))
ER48944 <- rename(ER48944, c('variable' = 'ER48944'))
ER16404 <- rename(ER16404, c('variable' = 'ER16404'))
ER27694 <- rename(ER27694, c('variable' = 'ER27694'))
ER16408 <- rename(ER16408, c('variable' = 'ER16408'))
ER27698 <- rename(ER27698, c('variable' = 'ER27698'))
V7297 <- rename(V7297, c('variable' = 'V7297'))
V7310 <- rename(V7310, c('variable' = 'V7310'))
ER16407 <- rename(ER16407, c('variable' = 'ER16407'))
ER27697 <- rename(ER27697, c('variable' = 'ER27697'))
ER16405 <- rename(ER16405, c('variable' = 'ER16405'))
ER27695 <- rename(ER27695, c('variable' = 'ER27695'))
ER16403 <- rename(ER16403, c('variable' = 'ER16403'))
ER27693 <- rename(ER27693, c('variable' = 'ER27693'))
ER16406 <- rename(ER16406, c('variable' = 'ER16406'))
ER27696 <- rename(ER27696, c('variable' = 'ER27696'))
ER16412   <- rename(ER16412  , c('variable' = 'ER16412'))
ER16402    <- rename(ER16402   , c('variable' = 'ER16402'))
ER27692 <- rename(ER27692, c('variable' = 'ER27692'))
ER37734 <- rename(ER37734, c('variable' = 'ER37734'))
ER37735 <- rename(ER37735, c('variable' = 'ER37735'))
ER37732 <- rename(ER37732, c('variable' = 'ER37732'))
ER37733 <- rename(ER37733, c('variable' = 'ER37733'))

#Merging multiple data frames
f1 <- Reduce(merge, list(V1164, V732, V733, V82, V11905, V734, V278, V11898, V11899, V11900, ER3711, ER3712, ER23735, ER48944, ER16404, ER27694, ER16408, ER27698, V7297, V7310, ER16407, ER27697, ER16405, ER27695, ER16403, ER27693, ER16406, ER27696, ER27692, ER37734, ER37735, ER37732, ER37733))


i1 <- Reduce(merge, list(ER33837, ER33535))

# We need to get rid of the Y preceeding the years and then destring the year variable
f1$year <- sub("Y", "", f1$year)
i1$year <- sub("Y", "", i1$year)

f1$year <- as.numeric(f1$year)
i1$year <- as.numeric(i1$year)

# Not sure if we need to try the steps below - added this while trying to figure out error
f1[] <- lapply(f1, as.character)
f1$year <- as.integer(f1$year)

d = build.panel(datadir=NULL,fam.vars=f1)
# must enter PSID username and password


```




`
